=== CoCoCompany/4850lab7/asset/data/timetable.dtd
<!ELEMENT data (dayfacet,coursefacet,timefacet)>

<!ELEMENT day (booking?)>
<!ATTLIST day day (Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) >

<!ELEMENT course (booking?)>
<!ATTLIST course course (ACIT4620|ACIT4650|ACIT4660|ACIT4770|ACIT4850|ACIT4910) >

<!ELEMENT timeslot (booking?)>
<!ATTLIST timeslot clock CDATA >

<!ELEMENT booking (clock?,course?,day?,instructor,room)>
<!ATTLIST booking course CDATA >
<!ATTLIST booking day CDATA >
<!ATTLIST booking clock CDATA >
<!ATTLIST booking instructor CDATA >
<!ATTLIST booking room CDATA >

<!ELEMENT timefacet (timeslot+)>
<!ELEMENT dayfacet (day+)>
<!ELEMENT coursefacet (course+)>

=== CoCoCompany/4850lab7/asset/data/master.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "timetable.dtd">
<data>
	<dayfacet>
		<day day="Friday">
			<booking clock="8:30-10:30" course="ACIT4660" instructor="Steve" roon="SW9-206 />
		</day>
	</dayfacet>
	<coursefacet>
		<course course="ACIT4660">
			<booking clock="8:30-10:30" day="Friday" instructor="Steve" roon="SW9-206 />
		</course>
	</coursefacet>
	<timefacet>
		<timeslot time="8:30-9:30">
                    <booking course="ACIT4660" day="Friday" instructor="Steve" roon="SW9-206 />
		</timeslot>
	</timefacet>
</data>
