=== CoCoCompany/4850lab7/data/timetable.dtd
<!ELEMENT data (days,courses,timeschedule)>
<!ELEMENT days (day)+>
<!ELEMENT day (booking)+>
<!ELEMENT booking (timeslot?,course?,day?,instructor,room)>
<!ELEMENT timeslot (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT timesfacet (timeslots)+>
<!ELEMENT timeslots (booking)+>

=== CoCoCompany/4850lab7/data/master.xml
<?xml version="1.0"?>
<!DOCTYPE data SYSTEM "timetable.dtd" [
<!ENTITY days SYSTEM "days.xml">
<!ENTITY courses SYSTEM "courses.xml">
<!ENTITY times SYSTEM "times.xml">
]>
<data>
  <days>
    <day day="Friday">
  		<booking>
  			<timeslot>8:30-9:30</timeslot>
  			<course>ACIT4660</course>
  			<instructor>Steve Fabz</instructor>
  			<room>SW9-206</room>
  		</booking>
  	</day>
  </days>
  <courses>
    <course course="ACIT4660">
      <booking>
        <timeslot>8:30-9:30</timeslot>
        <instructor>Steve Fabz</instructor>
        <room>SW9-206</room>
        <day>Friday</day>
      </booking>
    </course>
  </courses>
	<timefacet>
		<timeslot>8:30-9:30</timeslot>
			<whichday>
				<day>friday</day>
					<booking>
						<coursename>ACIT4660</coursename>
						<instructor>Steve Fabwd</instructor>
						<room>SW9 206</room>
					<booking>
			</whichday>
	</timefacet>
</data>
